services:

  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: test_db
    ports:
      - 3306:3306

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-CU5-ubuntu-18.04
    ports:
      - 1433:1433

    environment:
      - MSSQL_SA_PASSWORD=<YourStrong@Passw0rd>
    command: ["/opt/mssql/bin/sqlservr", "--accept-eula", "--reset-sa-password"]
