# This workflows will upload a Crates using cargo when a release is created
name: Upload Cargo Crates

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install latest rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        default: true
        override: true
    - name: Publish odbc-api to cargo
      env:
        CARGO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
      run: |
        cargo publish --token "${CARGO_TOKEN}" --package odbc-api-derive
        cargo publish --token "${CARGO_TOKEN}" --package odbc-api