# This workflows will build and release odbcsv
name: Deploy odbcsv

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'odbcsv*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  deploy_crates_io:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install latest rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        default: true
        override: true
    - name: Publish odbcsv to cargo
      env:
        CARGO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
      run: |
        cd odbcsv && cargo publish --token "${CARGO_TOKEN}"

  release_win64:
    name: Build and release Windows 64Bit
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install latests rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-msvc
          default: true
          override: true

      - name: Build
        run: |
          cargo build --release
          Compress-Archive -LiteralPath target/release/odbcsv.exe -DestinationPath odbcsv-win64.zip

      - name: Github Upload
        uses: svenstaro/upload-release-action@2.7.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: odbcsv-win64.zip
          asset_name: odbcsv-win64.zip
          tag: ${{ github.ref }}
  
  release_win32:
    name: Build and release Windows 32Bit
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install latests rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: i686-pc-windows-msvc
          default: true
          override: true

      - name: Build
        run: |
          cargo build --release
          Compress-Archive -LiteralPath target/release/odbcsv.exe -DestinationPath odbcsv-win32.zip

      - name: Github Upload
        uses: svenstaro/upload-release-action@2.7.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: odbcsv-win32.zip
          asset_name: odbcsv-win32.zip
          tag: ${{ github.ref }}

  release_os-x:
    name: Build and release OS-X
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Insall latests rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Build
        run: cargo build --release

      - name: Github Upload
        uses: svenstaro/upload-release-action@2.7.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/odbcsv
          asset_name: odbcsv-osx
          tag: ${{ github.ref }}